import Head from 'next/head';
import Image from 'next/image';
import Feed from '../components/Feed';
import Modal from '../components/Modal';
import Sidebar from '../components/Sidebar';
import Widget from '../components/Widget';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex w-full'>
        <Sidebar />
        <div className='w-full'>
          <div className='sticky top-0  bg-opacity-80 bg-[#202020] z-10 backdrop-blur-lg'>
            <h1 className='text-xl p-4'>Latest Tweets</h1>
          </div>
          <Feed />
          <div className='flex-col'>
            <Feed />
            <Feed />
            <Feed />
            <Feed />
            <Feed />
            <Feed />
          </div>
        </div>
        <Widget />

        <Modal />
      </div>
    </div>
  );
}
